/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    CreateProduct: typeof import('./src/components/CreateProduct.vue')['default']
    EditProduct: typeof import('./src/components/EditProduct.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MainComponent: typeof import('./src/components/MainComponent.vue')['default']
    Product: typeof import('./src/components/product.vue')['default']
    ProductForm: typeof import('./src/components/ProductForm.vue')['default']
    ProductList: typeof import('./src/components/ProductList.vue')['default']
    ProductTable: typeof import('./src/components/ProductTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
